### ISSUE TITLE
Logo for the app

### ISSUE THREAD

**Issue by Vivek-Py** [Vivek-Py/animehhunter#4]
App feels empty without a proper logo.

**Comment by Innanov** [comment]
![Anime Hunter Logo](https://user-images.githubusercontent.com/64653897/125157565-b59e6280-e163-11eb-8fdc-e5ea6a14885e.png)

**Comment by Vivek-Py** [comment]
This looks awesome, great job @Innanov

**Comment by Vivek-Py** [comment]
@all-contributors please add @Innanov  for Design and Graphics
